import Config
config :ash, policies: [show_policy_breakdowns?: true]

# Map tile source for development.
# Supports PMTiles vector tiles (pmtiles://...) or raster tile templates ({z}/{x}/{y}).
# For vector tiles, download a regional extract from https://protomaps.com/builds.
# The OSM raster fallback below works without any downloads.
config :platser,
       :pmtiles_url,
       "https://tile.openstreetmap.org/{z}/{x}/{y}.png"

# Configure your database
config :platser, Platser.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "platser_dev",
  types: Platser.PostgresTypes,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :platser, PlatserWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "BQVJ11JUkUJrV5zC1IRcstNLgEzzUzbFXj1Le58nt8MyQJKLzs8JRsO0ihtgpfMg",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:platser, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:platser, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :platser, PlatserWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/platser_web/router\.ex$",
      ~r"lib/platser_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :platser, dev_routes: true, token_signing_secret: "dWl+pCLneJ/+Yu5BWWiSBHtMPLaC0j/C"

# Start the GPS simulator in dev
config :platser, start_gps_simulator: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
