defmodule Platser.Repo.Migrations.AddIsGuestToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :is_guest, :boolean, default: false
    end
  end

  def down do
    alter table(:users) do
      remove :is_guest
    end
  end
end
