defmodule Platser.Repo.Migrations.AddSuperuserToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :superuser, :boolean, default: false
    end

    create unique_index(:media_attachments, [:path], name: "media_attachments_unique_path_index")
  end

  def down do
    drop_if_exists unique_index(:media_attachments, [:path],
                     name: "media_attachments_unique_path_index"
                   )

    alter table(:users) do
      remove :superuser
    end
  end
end
